services:
  headtts:
    build:
      context: ./headtts
      dockerfile: Dockerfile
      args:
        GIT_REF: v1.1.1   # pin the release (see repo releases)
    container_name: headtts
    expose:
      - "8882"
    networks:
      - supabase_default
    # Persist voices/dictionaries so the first-run downloads are cached
    volumes:
      - ./headtts/cache/voices:/app/voices
      - ./headtts/cache/dictionaries:/app/dictionaries
      - ./headtts/cache/transformers:/app/.cache   # NEW: persist Transformers.js cache
      # If you prefer to edit config locally, uncomment this and remove COPY in Dockerfile:
      - ./headtts/headtts-config.json:/app/headtts-node.json:ro
    # Optional healthcheck: HeadTTS root returns a greeting that starts with "HeadTTS"
    #healthcheck:
     # test: ["CMD-SHELL", "wget -qO- http://localhost:8882/ | grep -q HeadTTS"]
      #interval: 30s
      #timeout: 5s
      #retries: 5
      #start_period: 20s
    restart: unless-stopped
    environment:
      TZ: 'Europe/Berlin'

  akuapp:
    container_name: student
    build:
      context: .
    restart: unless-stopped
    # You don't need to publish the port to the host when using NPM
    # ports:
    #  - "8080:8080"
    environment:
      - VITE_AKU_API_URL=http://api.localhost
      - VITE_HEADTTS_URL=http://headtts.localhost
      # Ensure your dev server binds to all interfaces (adjust to your app)
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - supabase_default
    #depends_on:
     # headtts:
      #  condition: service_healthy 

networks:
  supabase_default:
    external: true
